INSERT INTO M_SYSTEM(CD, SYSTEM_NAME, NOTE, BIK, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('','','','','1',now(),'SYSTEM',now(),'SYSTEM');


INSERT INTO M_MENU(ID, NAME, URL, BIKO, YUKO_FLAG) VALUES ( '001','作業リスト','SideMenuPage','','1');
INSERT INTO M_MENU(ID, NAME, URL, BIKO, YUKO_FLAG) VALUES ( '002','メニューマスタ','MasterPage','','1');
INSERT INTO M_MENU(ID, NAME, URL, BIKO, YUKO_FLAG) VALUES ( '003','システムマスタ','','','1');
INSERT INTO M_MENU(ID, NAME, URL, BIKO, YUKO_FLAG) VALUES ( '004','プロジェクトマスタ','','','1');
INSERT INTO M_MENU(ID, NAME, URL, BIKO, YUKO_FLAG) VALUES ( '005','グループマスタ','','','1');
INSERT INTO M_MENU(ID, NAME, URL, BIKO, YUKO_FLAG) VALUES ( '006','コードトマスタ','','','1');


INSERT INTO M_PROJECT(SYSTEM_CD, CD, PROJECT_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001', '001', 'FRS-AG-SYS', '', '', '1', now(), 'SYSTEM', now(), 'SYSTEM');
INSERT INTO M_PROJECT(SYSTEM_CD, CD, PROJECT_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001', '002', 'FRS-GI-SYS', '', '', '1', now(), 'SYSTEM', now(), 'SYSTEM');
INSERT INTO M_PROJECT(SYSTEM_CD, CD, PROJECT_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001', '003', 'FRS-AS-SYS', '', '', '1', now(), 'SYSTEM', now(), 'SYSTEM');
INSERT INTO M_PROJECT(SYSTEM_CD, CD, PROJECT_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001', '004', 'FRS-PP-SYS', '', '', '1', now(), 'SYSTEM', now(), 'SYSTEM');
INSERT INTO M_PROJECT(SYSTEM_CD, CD, PROJECT_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001', '005', 'FRS-PO-SYS', '', '', '1', now(), 'SYSTEM', now(), 'SYSTEM');
INSERT INTO M_PROJECT(SYSTEM_CD, CD, PROJECT_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001', '006', 'FRS-PO-HOME', '', '', '1', now(), 'SYSTEM', now(), 'SYSTEM');
INSERT INTO M_PROJECT(SYSTEM_CD, CD, PROJECT_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001', '007', 'FRS-AM-SYS', '', '', '1', now(), 'SYSTEM', now(), 'SYSTEM');
INSERT INTO M_PROJECT(SYSTEM_CD, CD, PROJECT_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001', '008', 'FRS-SA-SYS', '', '', '1', now(), 'SYSTEM', now(), 'SYSTEM');
INSERT INTO M_PROJECT(SYSTEM_CD, CD, PROJECT_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001', '009', 'FRS-CO-SYS', '', '', '1', now(), 'SYSTEM', now(), 'SYSTEM');
INSERT INTO M_PROJECT(SYSTEM_CD, CD, PROJECT_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001', '010', 'FRS-MA-SYS', '', '', '1', now(), 'SYSTEM', now(), 'SYSTEM');
INSERT INTO M_PROJECT(SYSTEM_CD, CD, PROJECT_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001', '011', '利用情報', '', '', '1', now(), 'SYSTEM', now(), 'SYSTEM');

INSERT INTO M_CODE(GR_CD, CD, CD_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001','001','未着手','','','1',now(),'SYSTEM',now(),'SYSTEM');
INSERT INTO M_CODE(GR_CD, CD, CD_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001','002','着手中','','','1',now(),'SYSTEM',now(),'SYSTEM');
INSERT INTO M_CODE(GR_CD, CD, CD_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001','003','完了','','','1',now(),'SYSTEM',now(),'SYSTEM');
INSERT INTO M_CODE(GR_CD, CD, CD_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001','004','保留','','','1',now(),'SYSTEM',now(),'SYSTEM');
INSERT INTO M_CODE(GR_CD, CD, CD_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001','005','中止','','','1',now(),'SYSTEM',now(),'SYSTEM');
INSERT INTO M_CODE(GR_CD, CD, CD_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001','006','破棄','','','1',now(),'SYSTEM',now(),'SYSTEM');
INSERT INTO M_CODE(GR_CD, CD, CD_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('002','001','未','','','1',now(),'SYSTEM',now(),'SYSTEM');
INSERT INTO M_CODE(GR_CD, CD, CD_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('002','002','開発','','','1',now(),'SYSTEM',now(),'SYSTEM');
INSERT INTO M_CODE(GR_CD, CD, CD_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('002','003','試運用','','','1',now(),'SYSTEM',now(),'SYSTEM');
INSERT INTO M_CODE(GR_CD, CD, CD_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('002','004','準本番','','','1',now(),'SYSTEM',now(),'SYSTEM');
INSERT INTO M_CODE(GR_CD, CD, CD_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('002','005','本番','','','1',now(),'SYSTEM',now(),'SYSTEM');

INSERT INTO M_GROUP_CODE(CD, CD_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('001','進捗状況','','','1',now(),'SYSTEM',now(),'SYTEM');
INSERT INTO M_GROUP_CODE(CD, CD_NAME, NOTE, BIKO, YUKO_FLAG, INS_DATE, INS_USER_ID, UPD_DATE, UPD_USER_ID) 
VALUES ('002','デプロイ状況','','','1',now(),'SYSTEM',now(),'SYTEM');
