CREATE TABLE MEMO_PAD (
  CATEGORY_CD varchar(2) NOT NULL COMMENT 'カテゴリ_CD',
  LAEGE_KBN varchar(2) NOT NULL COMMENT '大区分',
  SUB_KBN varchar(3) NOT NULL COMMENT '中区分',
  SMALL_KBN varchar(3) NOT NULL COMMENT '小区分',
  TITLE varchar(255)  NULL COMMENT 'タイトル',
  MEMO TEXT  NULL COMMENT 'メモ',
  BIKO varchar(4000)  NULL COMMENT '備考',
   PRIMARY KEY (CATEGORY_CD, LAEGE_KBN, SUB_KBN, SMALL_KBN)
 ) DEFAULT CHARSET=utf8mb4 COMMENT='メモ帳'

